tools:
  php_sim: true
  php_pdepend: true
  php_analyzer: true
filter:
  excluded_paths:
    - tests/*
  paths:
    - src/*
checks:
  php: true
build:
  tests:
    override:
      -
        command: phpunit --coverage-clover=reCaptcha.clover
        coverage:
          file: reCaptcha.clover
          format: php-clover
